In [56]:
import pandas as pd

"""
ru_names.csv was manually created from the following sources:
I asked ChatGPT to generate 100 both female and male names and created a csv file from the output.
Currently, the file contains 200 names.
It is in my Google Docs
https://docs.google.com/spreadsheets/d/1Iz6NBs5LkMiLeUqzbOCRHZh6yifyM2JCGRVrFhlo_SE/edit#gid=0
"""
df_ru_names = pd.read_csv('ru_names.csv')       
df_ru_names.head()

  ru_male_name eng_male_name ru_female_name eng_female_name
0    Александр     Alexander           Анна            Anna
1       Андрей        Andrey          Ольга            Olga
2      Дмитрий        Dmitry        Татьяна         Tatyana
3         Иван          Ivan          Елена           Elena
4       Сергей        Sergey        Наталья         Natalia

In [63]:
# Download a csv with the column which contains the found crypto wallets and bank accounts. 
# We can assosiate the wallets/accounts with the names/posts.
# A CSV was created in the chat_Rosich.ipynb
df_chat = pd.read_csv('output/chat_Rosich_cryptoW.csv')
df_chat['text'] = df_chat['text'].fillna('')
# deselect empty rows
df_chat = df_chat[df_chat['text'] != '']
df_chat.head()

,time,time_tt,text,date,date_tt,credit_card,crypto
3,10:09:30,27.10.2022 10:09:30 UTC+02:00,Су-24 Оркестра пролетает над позициями НВФ 404...,27.10.2022,2022-10-27,[],NaN
4,10:42:18,27.10.2022 10:42:18 UTC+02:00,❗️Воздушная тревога на Украине@rosich_ru,27.10.2022,2022-10-27,[],NaN
5,10:43:14,27.10.2022 10:43:14 UTC+02:00,Воздушная тревога объявлена в Киеве@rosich_ru,27.10.2022,2022-10-27,[],NaN
6,10:47:08,27.10.2022 10:47:08 UTC+02:00,Во многих областях Украины объявлена воздушная...,27.10.2022,2022-10-27,[],NaN
7,10:48:57,27.10.2022 10:48:57 UTC+02:00,Коммерческие спутники США в случае их задейств...,27.10.2022,2022-10-27,[],NaN

In [70]:
### FIND MALE NAMES IN TEXT ###

import re
names_list = df_ru_names['ru_male_name'].tolist()

# Function to find names and surnames in text

def find_names(text, names_list):
    found_names = []
    for name in names_list:
        # Regex to find name possibly followed by a surname
        """
        not extracting a surname before a name, improve in the future
        """
        pattern = r'\b' + re.escape(name) + r'\s+[А-Я][а-я]+'
        matches = re.findall(pattern, text)

        found_names.extend(matches)
    return found_names

# Apply the function to each row in df['text']
df_chat['extracted_names'] = df_chat['text'].apply(lambda x: find_names(x, names_list))

# Display the result
display(df_chat.head(10))

,time,time_tt,text,date,date_tt,credit_card,crypto,extracted_names
3,10:09:30,27.10.2022 10:09:30 UTC+02:00,Су-24 Оркестра пролетает над позициями НВФ 404...,27.10.2022,2022-10-27,[],NaN,[]
4,10:42:18,27.10.2022 10:42:18 UTC+02:00,❗️Воздушная тревога на Украине@rosich_ru,27.10.2022,2022-10-27,[],NaN,[]
5,10:43:14,27.10.2022 10:43:14 UTC+02:00,Воздушная тревога объявлена в Киеве@rosich_ru,27.10.2022,2022-10-27,[],NaN,[]
6,10:47:08,27.10.2022 10:47:08 UTC+02:00,Во многих областях Украины объявлена воздушная...,27.10.2022,2022-10-27,[],NaN,[]
7,10:48:57,27.10.2022 10:48:57 UTC+02:00,Коммерческие спутники США в случае их задейств...,27.10.2022,2022-10-27,[],NaN,[Константин Воронцов]
8,12:30:43,27.10.2022 12:30:43 UTC+02:00,Пост для всех неравнодушных с той стороны. • Е...,27.10.2022,2022-10-27,[],NaN,[]
9,16:59:46,27.10.2022 16:59:46 UTC+02:00,Админы Росича в ожидании выступления Первого 😎...,27.10.2022,2022-10-27,[],NaN,[]
10,17:50:18,27.10.2022 17:50:18 UTC+02:00,Китай намерен поддерживать Россию в преодолени...,27.10.2022,2022-10-27,[],NaN,[]
11,18:21:36,27.10.2022 18:21:36 UTC+02:00,"Путин заявил, что не считает, что противника в...",27.10.2022,2022-10-27,[],NaN,[]
12,18:38:29,27.10.2022 18:38:29 UTC+02:00,Путин посоветовал почитать ядерную доктрину РФ...,27.10.2022,2022-10-27,[],NaN,[]

In [71]:
# split the column 'extracted_names' into rows by comma
df_chat = df_chat.explode('extracted_names')

# drop duplicates in the column 'extracted_names' and 'text'
df_chat = df_chat.drop_duplicates(subset=['extracted_names', 'text'])

# filter out rows with empty values in the column 'extracted_names'
df_chat = df_chat[df_chat['extracted_names'] != '']

# filter out rows with NaN values in the column 'extracted_names'
df_chat = df_chat[df_chat['extracted_names'].notna()]
df_chat.head(5)

,time,time_tt,text,date,date_tt,credit_card,crypto,extracted_names
7,10:48:57,27.10.2022 10:48:57 UTC+02:00,Коммерческие спутники США в случае их задейств...,27.10.2022,2022-10-27,[],NaN,Константин Воронцов
20,21:08:41,27.10.2022 21:08:41 UTC+02:00,Отличный юмор Владимир Владимирович 🤙@rosich_ru,27.10.2022,2022-10-27,[],NaN,Владимир Владимирович
50,17:11:56,28.10.2022 17:11:56 UTC+02:00,"Сергей Шойгу на встрече с Путиным: ""Установле...",28.10.2022,2022-10-28,[],NaN,Сергей Шойгу
81,12:53:04,29.10.2022 12:53:04 UTC+02:00,⚡️ Атака БПЛА в акватории Севастополя была сам...,29.10.2022,2022-10-29,[],NaN,Михаил Развожаев
105,23:36:26,29.10.2022 23:36:26 UTC+02:00,"Уехавшие в Грузию россияне заметили, что улицы...",29.10.2022,2022-10-29,[],NaN,Андрей Митрошин

In [72]:
# save the dataframe to csv
df_chat.to_csv('output/ru_male_names_extracted.csv', index=False, encoding='utf-8-sig')
df_chat

,time,time_tt,text,date,date_tt,credit_card,crypto,extracted_names
7,10:48:57,27.10.2022 10:48:57 UTC+02:00,Коммерческие спутники США в случае их задейств...,27.10.2022,2022-10-27,[],NaN,Константин Воронцов
20,21:08:41,27.10.2022 21:08:41 UTC+02:00,Отличный юмор Владимир Владимирович 🤙@rosich_ru,27.10.2022,2022-10-27,[],NaN,Владимир Владимирович
50,17:11:56,28.10.2022 17:11:56 UTC+02:00,"Сергей Шойгу на встрече с Путиным: ""Установле...",28.10.2022,2022-10-28,[],NaN,Сергей Шойгу
81,12:53:04,29.10.2022 12:53:04 UTC+02:00,⚡️ Атака БПЛА в акватории Севастополя была сам...,29.10.2022,2022-10-29,[],NaN,Михаил Развожаев
105,23:36:26,29.10.2022 23:36:26 UTC+02:00,"Уехавшие в Грузию россияне заметили, что улицы...",29.10.2022,2022-10-29,[],NaN,Андрей Митрошин
...,...,...,...,...,...,...,...,...
17307,07:13:24,15.11.2022 07:13:24 UTC+02:00,ВСУ не забирают тела своих погибших с линии со...,15.11.2022,2022-11-15,[],NaN,Владимир Рогов
17321,13:16:09,15.11.2022 13:16:09 UTC+02:00,⚡️Каховская ГЭС прекратила вырабатывать электр...,15.11.2022,2022-11-15,[],NaN,Владимир Сальдо
17397,21:08:53,15.11.2022 21:08:53 UTC+02:00,Во время выполнения служебно боевой задачи в з...,15.11.2022,2022-11-15,[],NaN,Дмитрий Александрович
17398,21:12:11,15.11.2022 21:12:11 UTC+02:00,Дмитрий Александрович в зоне СВО@rosich_ru,15.11.2022,2022-11-15,[],NaN,Дмитрий Александрович
17400,21:24:38,15.11.2022 21:24:38 UTC+02:00,⚡️⚡️Польский военный эксперт Ярослав Вольский ...,15.11.2022,2022-11-15,[],NaN,Ярослав Вольский

In [73]:
# deselect a column 'text'
df_chat = df_chat.drop(['text'], axis=1)
df_chat.to_csv('output/male_names_extracted_noText.csv', index=False, encoding='utf-8-sig')